require("PRUEBAS_1")
print("**Perfil de este wey...**")
print("Nombre:",nombre,apellidos)
print("viejometro:",edad)
print("-------------------------------------------------------")
print("Celulares",dispositivos.celulares,"Laptops:",dispositivos.laptop,"Pc's:",dispositivos.pc,"consolas:",dispositivos.consolas)
print("sueldo neto que ganaré (talvez):",futuro_sueldo)
print("lenguajes que se o que estoy aprendiendo:",lenguajes_de_progra[1],"Y",lenguajes_de_progra[6])
print("¿La casa cuenta con servicio electrico en este momento?:",luz_en_casa)